name: Build && Deploy Sanity Studio

on:
  push:
    paths:
      - "studio/*"
  workflow_dispatch:

jobs:
  sanity-deploy:
    runs-on: ubuntu-18.04
    name: Deploy Sanity
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "17.x"
      - uses: sanity-io/github-action-sanity@v0.2-alpha
      - name: Install Sanity CLI
        run: npm install -g @sanity/cli
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        with:
          args: deploy
